apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  labels:
    app: playground-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-helloworld
  template:
    metadata:
      labels:
        app: playground-helloworld
    spec:
      containers:
      - name: playground
        image: edwinlunando/playground:latest
        ports:
        - containerPort: 3000
