apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  labels:
    app: playground-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-helloworld
  template:
    metadata:
      labels:
        app: playground-helloworld
    spec:
      containers:
        - name: playground
          image: docker.pkg.github.com/edwinlunando/playground/latest:8c63f64b50473bff57dc388f3b3665017a530de5
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILS_LOG_TO_STDOUT
              value: "1"
          envFrom:
            - secretRef:
                name: secret-env
      imagePullSecrets:
        - name: regcred
