name: Deploy with Capistrano

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.7
    - name: Install prerequisite
      run: sudo apt update && sudo apt install sqlite3 libsqlite3-dev
    - name: Install dependencies
      run: bundle install
    - uses: miloserdow/capistrano-deploy@v2.1
      with:
        target: production
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY_PASSWORD }}
